### ISSUE TITLE
how Delvin is different than OpenDevin?

### ISSUE THREAD

**Issue by ramsey-coding** [opper-ai/delvin#1]
how Delvin is different than OpenDevin and SWE-agent? Please help to understand.

**Comment by psykhi** [comment]
You can see the architecture in the README. The code is very simple too, I can recommend reading it!

**Comment by ramsey-coding** [comment]
What's the purpose of [Opper](https://opper.ai/) SDK?

**Comment by psykhi** [comment]
Our SDK and backend work to make writing code with LLMs simpler. See our docs [here](https://docs.opper.ai/)

**Comment by ramsey-coding** [comment]
But now it needs an [Opper](https://opper.ai/) API key!

**Comment by ramsey-coding** [comment]
So much dependency for parsing LLM output. I love the idea, but another extra dependency to a third party 😢

**Comment by psykhi** [comment]
Yeah this is very fair feedback and I totally understand that you don't want to have one more dep! Feel free to sign up on the website if you want access!

**Comment by ramsey-coding** [comment]
@psykhi thanks. Is there a plan to open source some parts of the code that you are using for this agent as an example.

**Comment by psykhi** [comment]
Well the agent code is fully open source :D

We don't have plans to open source our platform at the moment, but will soon make it self serve so you could just go there and use our free tier to try it. Totally understand if you don't want to depend on a third party provider! 🙏
